name: Update npm dependencies and restart pm2 process

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted

        steps:
          - uses: actions/checkout@v2

          - name: Install dependencies
            run: npm install

          - name: Restart chess page
            run: sudo pm2 restart chess